name: smartcontract testing

on:
  push:
    branches: [ "master" ]

jobs:
  install-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: bahmutov/npm-install@v1

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node packages
        run: npm i

      - name: Run tests
        run: npm test
