name: smartcontract testing

on:
  push:
    branches: [ "master" ]

jobs:
  install-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node packages
        run: chmod +x ci.sh && ./ci.sh
